export interface FnoStockItem {
  symbol: string;
  name: string;
  sector: string;
  lotSize: number;
  strikeStep: number;
  baseIV: number;
  defaultPrice: number;
}

export const COMPLETE_NSE_FNO_STOCKS: FnoStockItem[] = [
  // --- AUTOMOBILE & ANCILLARIES ---
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd', sector: 'Auto & EV', lotSize: 700, strikeStep: 10, baseIV: 0.28, defaultPrice: 985.60 },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India', sector: 'Auto & EV', lotSize: 50, strikeStep: 100, baseIV: 0.23, defaultPrice: 11450.00 },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Auto & EV', lotSize: 200, strikeStep: 50, baseIV: 0.27, defaultPrice: 2950.00 },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd', sector: 'Auto & EV', lotSize: 75, strikeStep: 100, baseIV: 0.25, defaultPrice: 9680.00 },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd', sector: 'Auto & EV', lotSize: 150, strikeStep: 50, baseIV: 0.26, defaultPrice: 4850.00 },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd (Royal Enfield)', sector: 'Auto & EV', lotSize: 150, strikeStep: 50, baseIV: 0.25, defaultPrice: 4890.00 },
  { symbol: 'TVSMOTOR', name: 'TVS Motor Company', sector: 'Auto & EV', lotSize: 350, strikeStep: 20, baseIV: 0.27, defaultPrice: 2450.00 },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland Ltd', sector: 'Auto & EV', lotSize: 2500, strikeStep: 2.5, baseIV: 0.29, defaultPrice: 228.00 },
  { symbol: 'BHARATFORG', name: 'Bharat Forge Ltd', sector: 'Auto & EV', lotSize: 500, strikeStep: 20, baseIV: 0.28, defaultPrice: 1380.00 },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries', sector: 'Auto & EV', lotSize: 200, strikeStep: 50, baseIV: 0.27, defaultPrice: 2850.00 },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres Ltd', sector: 'Auto & EV', lotSize: 1700, strikeStep: 5, baseIV: 0.31, defaultPrice: 510.00 },
  { symbol: 'MRF', name: 'MRF Ltd (Tyres)', sector: 'Auto & EV', lotSize: 5, strikeStep: 500, baseIV: 0.21, defaultPrice: 128500.00 },
  { symbol: 'MOTHERSON', name: 'Samvardhana Motherson', sector: 'Auto & EV', lotSize: 3100, strikeStep: 2.5, baseIV: 0.32, defaultPrice: 165.00 },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd', sector: 'Auto & EV', lotSize: 25, strikeStep: 200, baseIV: 0.24, defaultPrice: 34500.00 },
  { symbol: 'EXIDEIND', name: 'Exide Industries Ltd', sector: 'Auto & EV', lotSize: 1200, strikeStep: 5, baseIV: 0.34, defaultPrice: 480.00 },
  { symbol: 'AMARAJABAT', name: 'Amara Raja Energy & Mobility', sector: 'Auto & EV', lotSize: 450, strikeStep: 20, baseIV: 0.36, defaultPrice: 1280.00 },

  // --- BANKING & FINANCIAL SERVICES ---
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd', sector: 'Banking & Finance', lotSize: 550, strikeStep: 10, baseIV: 0.20, defaultPrice: 1785.40 },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd', sector: 'Banking & Finance', lotSize: 700, strikeStep: 10, baseIV: 0.21, defaultPrice: 1265.80 },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking & PSU', lotSize: 750, strikeStep: 10, baseIV: 0.25, defaultPrice: 842.10 },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking & Finance', lotSize: 400, strikeStep: 20, baseIV: 0.21, defaultPrice: 1740.00 },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd', sector: 'Banking & Finance', lotSize: 625, strikeStep: 10, baseIV: 0.24, defaultPrice: 1195.00 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd', sector: 'Banking & Finance', lotSize: 500, strikeStep: 20, baseIV: 0.30, defaultPrice: 1020.00 },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking & PSU', lotSize: 2425, strikeStep: 2.5, baseIV: 0.31, defaultPrice: 245.00 },
  { symbol: 'PNB', name: 'Punjab National Bank', sector: 'Banking & PSU', lotSize: 4000, strikeStep: 1, baseIV: 0.33, defaultPrice: 105.00 },
  { symbol: 'CANBK', name: 'Canara Bank', sector: 'Banking & PSU', lotSize: 4500, strikeStep: 1, baseIV: 0.32, defaultPrice: 102.50 },
  { symbol: 'FEDERALBNK', name: 'Federal Bank Ltd', sector: 'Banking & Finance', lotSize: 3000, strikeStep: 2.5, baseIV: 0.28, defaultPrice: 205.00 },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank', sector: 'Banking & Finance', lotSize: 7500, strikeStep: 1, baseIV: 0.35, defaultPrice: 65.00 },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank Ltd', sector: 'Banking & Finance', lotSize: 2600, strikeStep: 2.5, baseIV: 0.38, defaultPrice: 168.00 },
  { symbol: 'AUBANK', name: 'AU Small Finance Bank', sector: 'Banking & Finance', lotSize: 1000, strikeStep: 10, baseIV: 0.34, defaultPrice: 590.00 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd', sector: 'Banking & Finance', lotSize: 125, strikeStep: 50, baseIV: 0.26, defaultPrice: 6890.00 },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd', sector: 'Banking & Finance', lotSize: 500, strikeStep: 20, baseIV: 0.25, defaultPrice: 1820.00 },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment', sector: 'Banking & Finance', lotSize: 400, strikeStep: 20, baseIV: 0.28, defaultPrice: 1540.00 },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance Ltd', sector: 'Banking & Finance', lotSize: 150, strikeStep: 50, baseIV: 0.29, defaultPrice: 3250.00 },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd (Gold)', sector: 'Banking & Finance', lotSize: 350, strikeStep: 20, baseIV: 0.27, defaultPrice: 1890.00 },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance Ltd', sector: 'Banking & Finance', lotSize: 3000, strikeStep: 2.5, baseIV: 0.38, defaultPrice: 175.00 },
  { symbol: 'M&MFIN', name: 'Mahindra Financial Services', sector: 'Banking & Finance', lotSize: 2000, strikeStep: 5, baseIV: 0.33, defaultPrice: 280.00 },
  { symbol: 'PFC', name: 'Power Finance Corporation', sector: 'Banking & PSU', lotSize: 1300, strikeStep: 5, baseIV: 0.33, defaultPrice: 495.00 },
  { symbol: 'RECLTD', name: 'REC Ltd (Rural Electrification)', sector: 'Banking & PSU', lotSize: 1400, strikeStep: 5, baseIV: 0.34, defaultPrice: 560.00 },
  { symbol: 'L&TFH', name: 'L&T Finance Holdings', sector: 'Banking & Finance', lotSize: 4454, strikeStep: 2.5, baseIV: 0.35, defaultPrice: 155.00 },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance', sector: 'Banking & Finance', lotSize: 1100, strikeStep: 10, baseIV: 0.23, defaultPrice: 685.00 },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Banking & Finance', lotSize: 375, strikeStep: 20, baseIV: 0.22, defaultPrice: 1540.00 },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life', sector: 'Banking & Finance', lotSize: 750, strikeStep: 10, baseIV: 0.25, defaultPrice: 675.00 },
  { symbol: 'ICICIGI', name: 'ICICI Lombard General Ins', sector: 'Banking & Finance', lotSize: 350, strikeStep: 20, baseIV: 0.23, defaultPrice: 1880.00 },
  { symbol: 'HDFCAMC', name: 'HDFC Asset Management', sector: 'Banking & Finance', lotSize: 150, strikeStep: 50, baseIV: 0.26, defaultPrice: 4250.00 },
  { symbol: 'CDSL', name: 'Central Depository Services', sector: 'Banking & Finance', lotSize: 375, strikeStep: 20, baseIV: 0.33, defaultPrice: 1540.00 },
  { symbol: 'MCX', name: 'Multi Commodity Exchange', sector: 'Banking & Finance', lotSize: 125, strikeStep: 50, baseIV: 0.38, defaultPrice: 5850.00 },
  { symbol: 'BSE', name: 'BSE Ltd (Exchange)', sector: 'Banking & Finance', lotSize: 200, strikeStep: 50, baseIV: 0.42, defaultPrice: 4750.00 },
  { symbol: 'ANGELONE', name: 'Angel One Ltd', sector: 'Banking & Finance', lotSize: 250, strikeStep: 20, baseIV: 0.39, defaultPrice: 2850.00 },
  { symbol: 'JIOFIN', name: 'Jio Financial Services', sector: 'Banking & Finance', lotSize: 1800, strikeStep: 5, baseIV: 0.34, defaultPrice: 342.00 },

  // --- IT & TECH SERVICES ---
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT & Software', lotSize: 175, strikeStep: 50, baseIV: 0.21, defaultPrice: 4280.00 },
  { symbol: 'INFY', name: 'Infosys Ltd', sector: 'IT & Software', lotSize: 400, strikeStep: 20, baseIV: 0.24, defaultPrice: 1920.30 },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd', sector: 'IT & Software', lotSize: 350, strikeStep: 20, baseIV: 0.23, defaultPrice: 1780.00 },
  { symbol: 'WIPRO', name: 'Wipro Ltd', sector: 'IT & Software', lotSize: 1500, strikeStep: 10, baseIV: 0.24, defaultPrice: 545.00 },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd', sector: 'IT & Software', lotSize: 600, strikeStep: 20, baseIV: 0.26, defaultPrice: 1680.00 },
  { symbol: 'LTIM', name: 'LTIMindtree Ltd', sector: 'IT & Software', lotSize: 150, strikeStep: 50, baseIV: 0.28, defaultPrice: 5950.00 },
  { symbol: 'PERSISTENT', name: 'Persistent Systems Ltd', sector: 'IT & Software', lotSize: 100, strikeStep: 50, baseIV: 0.31, defaultPrice: 5650.00 },
  { symbol: 'COFORGE', name: 'Coforge Ltd', sector: 'IT & Software', lotSize: 75, strikeStep: 100, baseIV: 0.33, defaultPrice: 7850.00 },
  { symbol: 'MPHASIS', name: 'Mphasis Ltd', sector: 'IT & Software', lotSize: 275, strikeStep: 50, baseIV: 0.29, defaultPrice: 2950.00 },
  { symbol: 'LTTS', name: 'L&T Technology Services', sector: 'IT & Software', lotSize: 100, strikeStep: 50, baseIV: 0.28, defaultPrice: 5400.00 },
  { symbol: 'TATAELXSI', name: 'Tata Elxsi Ltd', sector: 'IT & Software', lotSize: 100, strikeStep: 50, baseIV: 0.30, defaultPrice: 6780.00 },
  { symbol: 'BSOFT', name: 'Birlasoft Ltd', sector: 'IT & Software', lotSize: 1000, strikeStep: 10, baseIV: 0.35, defaultPrice: 620.00 },
  { symbol: 'ZOMATO', name: 'Zomato Ltd (Blinkit)', sector: 'IT & Software', lotSize: 2000, strikeStep: 5, baseIV: 0.38, defaultPrice: 275.40 },
  { symbol: 'NAUKRI', name: 'Info Edge India (Naukri)', sector: 'IT & Software', lotSize: 75, strikeStep: 100, baseIV: 0.32, defaultPrice: 7650.00 },
  { symbol: 'KPITTECH', name: 'KPIT Technologies Ltd', sector: 'IT & Software', lotSize: 300, strikeStep: 20, baseIV: 0.35, defaultPrice: 1540.00 },
  { symbol: 'DIXON', name: 'Dixon Technologies Ltd', sector: 'IT & Software', lotSize: 50, strikeStep: 200, baseIV: 0.35, defaultPrice: 14200.00 },

  // --- ENERGY, OIL & POWER ---
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd', sector: 'Energy & Power', lotSize: 250, strikeStep: 20, baseIV: 0.22, defaultPrice: 2980.50 },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', sector: 'Energy & Power', lotSize: 2550, strikeStep: 2.5, baseIV: 0.27, defaultPrice: 265.00 },
  { symbol: 'IOC', name: 'Indian Oil Corporation', sector: 'Energy & Power', lotSize: 4875, strikeStep: 2.5, baseIV: 0.28, defaultPrice: 145.00 },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corp', sector: 'Energy & Power', lotSize: 1800, strikeStep: 5, baseIV: 0.29, defaultPrice: 310.00 },
  { symbol: 'HPCL', name: 'Hindustan Petroleum Corp', sector: 'Energy & Power', lotSize: 1350, strikeStep: 5, baseIV: 0.32, defaultPrice: 385.00 },
  { symbol: 'GAIL', name: 'GAIL India Ltd (Gas)', sector: 'Energy & Power', lotSize: 2925, strikeStep: 2.5, baseIV: 0.28, defaultPrice: 205.00 },
  { symbol: 'PETRONET', name: 'Petronet LNG Ltd', sector: 'Energy & Power', lotSize: 1800, strikeStep: 5, baseIV: 0.26, defaultPrice: 345.00 },
  { symbol: 'IGL', name: 'Indraprastha Gas Ltd', sector: 'Energy & Power', lotSize: 1375, strikeStep: 5, baseIV: 0.31, defaultPrice: 410.00 },
  { symbol: 'MGL', name: 'Mahanagar Gas Ltd', sector: 'Energy & Power', lotSize: 400, strikeStep: 20, baseIV: 0.28, defaultPrice: 1580.00 },
  { symbol: 'GUJGASLTD', name: 'Gujarat Gas Ltd', sector: 'Energy & Power', lotSize: 1250, strikeStep: 5, baseIV: 0.29, defaultPrice: 540.00 },
  { symbol: 'NTPC', name: 'NTPC Ltd', sector: 'Energy & Power', lotSize: 1500, strikeStep: 5, baseIV: 0.24, defaultPrice: 395.00 },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Energy & Power', lotSize: 1800, strikeStep: 5, baseIV: 0.22, defaultPrice: 325.00 },
  { symbol: 'TATAPOWER', name: 'Tata Power Company Ltd', sector: 'Energy & Power', lotSize: 1350, strikeStep: 5, baseIV: 0.30, defaultPrice: 420.00 },
  { symbol: 'ADANIPOWER', name: 'Adani Power Ltd', sector: 'Energy & Power', lotSize: 875, strikeStep: 10, baseIV: 0.42, defaultPrice: 580.00 },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy Ltd', sector: 'Energy & Power', lotSize: 600, strikeStep: 20, baseIV: 0.44, defaultPrice: 1120.00 },
  { symbol: 'ADANIENSOL', name: 'Adani Energy Solutions', sector: 'Energy & Power', lotSize: 700, strikeStep: 10, baseIV: 0.43, defaultPrice: 890.00 },
  { symbol: 'TORNTPOWER', name: 'Torrent Power Ltd', sector: 'Energy & Power', lotSize: 375, strikeStep: 20, baseIV: 0.35, defaultPrice: 1640.00 },
  { symbol: 'NHPC', name: 'NHPC Ltd (Hydro)', sector: 'Energy & Power', lotSize: 5500, strikeStep: 1, baseIV: 0.36, defaultPrice: 85.00 },
  { symbol: 'SJVN', name: 'SJVN Ltd', sector: 'Energy & Power', lotSize: 4500, strikeStep: 1, baseIV: 0.38, defaultPrice: 115.00 },
  { symbol: 'SUZLON', name: 'Suzlon Energy Ltd (Wind)', sector: 'Energy & Power', lotSize: 8000, strikeStep: 1, baseIV: 0.45, defaultPrice: 74.50 },
  { symbol: 'KPIGREEN', name: 'KPI Green Energy Ltd', sector: 'Energy & Power', lotSize: 500, strikeStep: 10, baseIV: 0.40, defaultPrice: 820.00 },
  { symbol: 'IREDA', name: 'Indian Renewable Energy Dev', sector: 'Energy & Power', lotSize: 2500, strikeStep: 5, baseIV: 0.41, defaultPrice: 215.00 },

  // --- METALS & MINING ---
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd', sector: 'Metals & Mining', lotSize: 5500, strikeStep: 2.5, baseIV: 0.29, defaultPrice: 154.50 },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd', sector: 'Metals & Mining', lotSize: 675, strikeStep: 10, baseIV: 0.26, defaultPrice: 985.00 },
  { symbol: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals & Mining', lotSize: 1400, strikeStep: 10, baseIV: 0.30, defaultPrice: 685.00 },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power', sector: 'Metals & Mining', lotSize: 625, strikeStep: 10, baseIV: 0.32, defaultPrice: 940.00 },
  { symbol: 'VEDL', name: 'Vedanta Ltd', sector: 'Metals & Mining', lotSize: 1150, strikeStep: 5, baseIV: 0.38, defaultPrice: 498.00 },
  { symbol: 'COALINDIA', name: 'Coal India Ltd', sector: 'Metals & Mining', lotSize: 2100, strikeStep: 5, baseIV: 0.24, defaultPrice: 410.00 },
  { symbol: 'NMDC', name: 'NMDC Ltd (Iron Ore)', sector: 'Metals & Mining', lotSize: 2700, strikeStep: 2.5, baseIV: 0.33, defaultPrice: 235.00 },
  { symbol: 'SAIL', name: 'Steel Authority of India', sector: 'Metals & Mining', lotSize: 4700, strikeStep: 1, baseIV: 0.36, defaultPrice: 125.00 },
  { symbol: 'NATIONALUM', name: 'National Aluminium Co', sector: 'Metals & Mining', lotSize: 3750, strikeStep: 2.5, baseIV: 0.37, defaultPrice: 225.00 },
  { symbol: 'HINDCOPPER', name: 'Hindustan Copper Ltd', sector: 'Metals & Mining', lotSize: 1750, strikeStep: 5, baseIV: 0.44, defaultPrice: 290.00 },

  // --- PHARMA & HEALTHCARE ---
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Ltd', sector: 'Healthcare & Pharma', lotSize: 350, strikeStep: 20, baseIV: 0.22, defaultPrice: 1820.00 },
  { symbol: 'DRREDDY', name: 'Dr. Reddys Laboratories', sector: 'Healthcare & Pharma', lotSize: 125, strikeStep: 50, baseIV: 0.23, defaultPrice: 6250.00 },
  { symbol: 'CIPLA', name: 'Cipla Ltd', sector: 'Healthcare & Pharma', lotSize: 650, strikeStep: 20, baseIV: 0.22, defaultPrice: 1540.00 },
  { symbol: 'DIVISLAB', name: 'Divis Laboratories Ltd', sector: 'Healthcare & Pharma', lotSize: 100, strikeStep: 50, baseIV: 0.26, defaultPrice: 5850.00 },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise', sector: 'Healthcare & Pharma', lotSize: 125, strikeStep: 50, baseIV: 0.25, defaultPrice: 6950.00 },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare Institute', sector: 'Healthcare & Pharma', lotSize: 550, strikeStep: 10, baseIV: 0.28, defaultPrice: 1020.00 },
  { symbol: 'LUPIN', name: 'Lupin Ltd', sector: 'Healthcare & Pharma', lotSize: 425, strikeStep: 20, baseIV: 0.28, defaultPrice: 2150.00 },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd', sector: 'Healthcare & Pharma', lotSize: 550, strikeStep: 20, baseIV: 0.29, defaultPrice: 1390.00 },
  { symbol: 'ALKEM', name: 'Alkem Laboratories Ltd', sector: 'Healthcare & Pharma', lotSize: 100, strikeStep: 50, baseIV: 0.24, defaultPrice: 5650.00 },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals', sector: 'Healthcare & Pharma', lotSize: 250, strikeStep: 50, baseIV: 0.23, defaultPrice: 3450.00 },
  { symbol: 'BIOCON', name: 'Biocon Ltd', sector: 'Healthcare & Pharma', lotSize: 2500, strikeStep: 5, baseIV: 0.33, defaultPrice: 340.00 },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences Ltd', sector: 'Healthcare & Pharma', lotSize: 900, strikeStep: 10, baseIV: 0.26, defaultPrice: 1040.00 },
  { symbol: 'IPCALAB', name: 'IPCA Laboratories Ltd', sector: 'Healthcare & Pharma', lotSize: 325, strikeStep: 20, baseIV: 0.27, defaultPrice: 1560.00 },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals', sector: 'Healthcare & Pharma', lotSize: 375, strikeStep: 20, baseIV: 0.32, defaultPrice: 1680.00 },
  { symbol: 'LAURUSLABS', name: 'Laurus Labs Ltd', sector: 'Healthcare & Pharma', lotSize: 1100, strikeStep: 5, baseIV: 0.35, defaultPrice: 475.00 },
  { symbol: 'SYNGENE', name: 'Syngene International', sector: 'Healthcare & Pharma', lotSize: 500, strikeStep: 10, baseIV: 0.26, defaultPrice: 890.00 },
  { symbol: 'GRANULES', name: 'Granules India Ltd', sector: 'Healthcare & Pharma', lotSize: 1000, strikeStep: 10, baseIV: 0.36, defaultPrice: 580.00 },

  // --- FMCG & CONSUMER GOODS ---
  { symbol: 'ITC', name: 'ITC Ltd', sector: 'FMCG & Consumer', lotSize: 1600, strikeStep: 5, baseIV: 0.19, defaultPrice: 495.20 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd', sector: 'FMCG & Consumer', lotSize: 300, strikeStep: 20, baseIV: 0.18, defaultPrice: 2480.00 },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd', sector: 'FMCG & Consumer', lotSize: 200, strikeStep: 20, baseIV: 0.19, defaultPrice: 2320.00 },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd', sector: 'FMCG & Consumer', lotSize: 125, strikeStep: 50, baseIV: 0.20, defaultPrice: 5100.00 },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products', sector: 'FMCG & Consumer', lotSize: 450, strikeStep: 10, baseIV: 0.22, defaultPrice: 1040.00 },
  { symbol: 'DABUR', name: 'Dabur India Ltd', sector: 'FMCG & Consumer', lotSize: 1250, strikeStep: 5, baseIV: 0.20, defaultPrice: 540.00 },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products', sector: 'FMCG & Consumer', lotSize: 500, strikeStep: 10, baseIV: 0.23, defaultPrice: 1220.00 },
  { symbol: 'MARICO', name: 'Marico Ltd (Parachute)', sector: 'FMCG & Consumer', lotSize: 1200, strikeStep: 5, baseIV: 0.21, defaultPrice: 645.00 },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive India', sector: 'FMCG & Consumer', lotSize: 175, strikeStep: 50, baseIV: 0.22, defaultPrice: 3150.00 },
  { symbol: 'VBL', name: 'Varun Beverages Ltd (Pepsi)', sector: 'FMCG & Consumer', lotSize: 1000, strikeStep: 10, baseIV: 0.28, defaultPrice: 620.00 },
  { symbol: 'UBL', name: 'United Breweries Ltd (Kingfisher)', sector: 'FMCG & Consumer', lotSize: 400, strikeStep: 20, baseIV: 0.26, defaultPrice: 2050.00 },
  { symbol: 'MCDOWELL-N', name: 'United Spirits Ltd (Diageo)', sector: 'FMCG & Consumer', lotSize: 400, strikeStep: 20, baseIV: 0.25, defaultPrice: 1520.00 },
  { symbol: 'RADICO', name: 'Radico Khaitan Ltd', sector: 'FMCG & Consumer', lotSize: 250, strikeStep: 20, baseIV: 0.32, defaultPrice: 2280.00 },
  { symbol: 'TITAN', name: 'Titan Company Ltd (Tanishq)', sector: 'FMCG & Consumer', lotSize: 175, strikeStep: 50, baseIV: 0.25, defaultPrice: 3420.00 },
  { symbol: 'TRENT', name: 'Trent Ltd (Westside & Zudio)', sector: 'FMCG & Consumer', lotSize: 100, strikeStep: 100, baseIV: 0.36, defaultPrice: 7850.00 },
  { symbol: 'PAGEIND', name: 'Page Industries (Jockey)', sector: 'FMCG & Consumer', lotSize: 15, strikeStep: 500, baseIV: 0.23, defaultPrice: 44500.00 },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion & Retail', sector: 'FMCG & Consumer', lotSize: 2600, strikeStep: 5, baseIV: 0.38, defaultPrice: 295.00 },
  { symbol: 'BATAINDIA', name: 'Bata India Ltd', sector: 'FMCG & Consumer', lotSize: 375, strikeStep: 20, baseIV: 0.24, defaultPrice: 1420.00 },

  // --- INFRASTRUCTURE, CAPITAL GOODS & DEFENSE ---
  { symbol: 'LT', name: 'Larsen & Toubro Ltd', sector: 'Infrastructure', lotSize: 175, strikeStep: 50, baseIV: 0.23, defaultPrice: 3640.10 },
  { symbol: 'HAL', name: 'Hindustan Aeronautics Ltd', sector: 'Defense & Aerospace', lotSize: 150, strikeStep: 50, baseIV: 0.32, defaultPrice: 4520.00 },
  { symbol: 'BEL', name: 'Bharat Electronics Ltd', sector: 'Defense & Aerospace', lotSize: 2850, strikeStep: 5, baseIV: 0.31, defaultPrice: 285.40 },
  { symbol: 'MAZDOCK', name: 'Mazagon Dock Shipbuilders', sector: 'Defense & Aerospace', lotSize: 150, strikeStep: 50, baseIV: 0.38, defaultPrice: 4250.00 },
  { symbol: 'COCHINSHIP', name: 'Cochin Shipyard Ltd', sector: 'Defense & Aerospace', lotSize: 350, strikeStep: 20, baseIV: 0.42, defaultPrice: 1780.00 },
  { symbol: 'BDL', name: 'Bharat Dynamics Ltd (Missiles)', sector: 'Defense & Aerospace', lotSize: 400, strikeStep: 20, baseIV: 0.40, defaultPrice: 1220.00 },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals', sector: 'Capital Goods', lotSize: 2625, strikeStep: 2.5, baseIV: 0.38, defaultPrice: 245.00 },
  { symbol: 'SIEMENS', name: 'Siemens Ltd India', sector: 'Capital Goods', lotSize: 75, strikeStep: 100, baseIV: 0.29, defaultPrice: 7200.00 },
  { symbol: 'ABB', name: 'ABB India Ltd', sector: 'Capital Goods', lotSize: 62, strikeStep: 100, baseIV: 0.30, defaultPrice: 8150.00 },
  { symbol: 'POLYCAB', name: 'Polycab India Ltd (Cables)', sector: 'Capital Goods', lotSize: 100, strikeStep: 50, baseIV: 0.28, defaultPrice: 6850.00 },
  { symbol: 'HAVELLS', name: 'Havells India Ltd', sector: 'Capital Goods', lotSize: 350, strikeStep: 20, baseIV: 0.26, defaultPrice: 1750.00 },
  { symbol: 'VOLTAS', name: 'Voltas Ltd (Tata AC)', sector: 'Capital Goods', lotSize: 300, strikeStep: 20, baseIV: 0.30, defaultPrice: 1680.00 },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer', sector: 'Capital Goods', lotSize: 1800, strikeStep: 5, baseIV: 0.30, defaultPrice: 410.00 },
  { symbol: 'ASTRAL', name: 'Astral Ltd (Pipes)', sector: 'Capital Goods', lotSize: 275, strikeStep: 20, baseIV: 0.29, defaultPrice: 1890.00 },
  { symbol: 'SUPREMEIND', name: 'Supreme Industries Ltd', sector: 'Capital Goods', lotSize: 125, strikeStep: 50, baseIV: 0.28, defaultPrice: 4850.00 },
  { symbol: 'CUMMINSIND', name: 'Cummins India Ltd', sector: 'Capital Goods', lotSize: 150, strikeStep: 50, baseIV: 0.29, defaultPrice: 3680.00 },
  { symbol: 'GMRINFRA', name: 'GMR Airports Infrastructure', sector: 'Infrastructure', lotSize: 5000, strikeStep: 1, baseIV: 0.36, defaultPrice: 86.00 },
  { symbol: 'RVNL', name: 'Rail Vikas Nigam Ltd', sector: 'PSU & Railways', lotSize: 1250, strikeStep: 10, baseIV: 0.39, defaultPrice: 445.00 },
  { symbol: 'IRCTC', name: 'IRCTC Ltd', sector: 'PSU & Railways', lotSize: 625, strikeStep: 10, baseIV: 0.27, defaultPrice: 895.00 },
  { symbol: 'IRFC', name: 'Indian Railway Finance Corp', sector: 'PSU & Railways', lotSize: 3500, strikeStep: 2.5, baseIV: 0.35, defaultPrice: 162.80 },
  { symbol: 'RITES', name: 'RITES Ltd (Railways)', sector: 'PSU & Railways', lotSize: 1250, strikeStep: 5, baseIV: 0.34, defaultPrice: 345.00 },
  { symbol: 'KAYNES', name: 'Kaynes Technology India', sector: 'Capital Goods', lotSize: 100, strikeStep: 50, baseIV: 0.37, defaultPrice: 5450.00 },

  // --- TELECOM & MEDIA ---
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd', sector: 'Telecom', lotSize: 475, strikeStep: 20, baseIV: 0.22, defaultPrice: 1680.50 },
  { symbol: 'INDUSTOWER', name: 'Indus Towers Ltd', sector: 'Telecom', lotSize: 1700, strikeStep: 5, baseIV: 0.39, defaultPrice: 355.00 },
  { symbol: 'TATACOMM', name: 'Tata Communications Ltd', sector: 'Telecom', lotSize: 250, strikeStep: 20, baseIV: 0.28, defaultPrice: 1980.00 },
  { symbol: 'IDEA', name: 'Vodafone Idea Ltd', sector: 'Telecom', lotSize: 50000, strikeStep: 0.25, baseIV: 0.75, defaultPrice: 7.40 },
  { symbol: 'ZEEL', name: 'Zee Entertainment Enterprises', sector: 'Media & Entertainment', lotSize: 3000, strikeStep: 2.5, baseIV: 0.52, defaultPrice: 118.00 },
  { symbol: 'PVRINOX', name: 'PVR INOX Ltd (Cinema)', sector: 'Media & Entertainment', lotSize: 400, strikeStep: 20, baseIV: 0.33, defaultPrice: 1460.00 },
  { symbol: 'SUNTV', name: 'Sun TV Network Ltd', sector: 'Media & Entertainment', lotSize: 750, strikeStep: 10, baseIV: 0.32, defaultPrice: 780.00 },

  // --- REALTY & CEMENT ---
  { symbol: 'DLF', name: 'DLF Ltd', sector: 'Realty & Construction', lotSize: 825, strikeStep: 10, baseIV: 0.33, defaultPrice: 890.00 },
  { symbol: 'GODREJPROP', name: 'Godrej Properties Ltd', sector: 'Realty & Construction', lotSize: 225, strikeStep: 50, baseIV: 0.36, defaultPrice: 2950.00 },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty Ltd', sector: 'Realty & Construction', lotSize: 350, strikeStep: 20, baseIV: 0.32, defaultPrice: 1920.00 },
  { symbol: 'LODHA', name: 'Macrotech Developers (Lodha)', sector: 'Realty & Construction', lotSize: 425, strikeStep: 20, baseIV: 0.35, defaultPrice: 1240.00 },
  { symbol: 'PRESTIGE', name: 'Prestige Estates Projects', sector: 'Realty & Construction', lotSize: 350, strikeStep: 20, baseIV: 0.38, defaultPrice: 1720.00 },
  { symbol: 'BRIGADE', name: 'Brigade Enterprises Ltd', sector: 'Realty & Construction', lotSize: 450, strikeStep: 20, baseIV: 0.36, defaultPrice: 1280.00 },
  { symbol: 'PHOENIXLTD', name: 'The Phoenix Mills Ltd', sector: 'Realty & Construction', lotSize: 350, strikeStep: 20, baseIV: 0.31, defaultPrice: 1650.00 },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd', sector: 'Cement & Materials', lotSize: 50, strikeStep: 100, baseIV: 0.22, defaultPrice: 11200.00 },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd', sector: 'Cement & Materials', lotSize: 225, strikeStep: 50, baseIV: 0.24, defaultPrice: 2680.00 },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd (Adani)', sector: 'Cement & Materials', lotSize: 900, strikeStep: 10, baseIV: 0.28, defaultPrice: 580.00 },
  { symbol: 'ACC', name: 'ACC Ltd (Cement)', sector: 'Cement & Materials', lotSize: 250, strikeStep: 20, baseIV: 0.27, defaultPrice: 2250.00 },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd', sector: 'Cement & Materials', lotSize: 25, strikeStep: 200, baseIV: 0.24, defaultPrice: 25800.00 },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat Ltd', sector: 'Cement & Materials', lotSize: 300, strikeStep: 20, baseIV: 0.29, defaultPrice: 1840.00 },
  { symbol: 'RAMCOCEM', name: 'The Ramco Cements Ltd', sector: 'Cement & Materials', lotSize: 650, strikeStep: 10, baseIV: 0.28, defaultPrice: 920.00 },
  { symbol: 'JKCEMENT', name: 'JK Cement Ltd', sector: 'Cement & Materials', lotSize: 125, strikeStep: 50, baseIV: 0.27, defaultPrice: 4350.00 },

  // --- CHEMICALS & FERTILISERS ---
  { symbol: 'PIDILITIND', name: 'Pidilite Industries (Fevicol)', sector: 'Chemicals & Fertilisers', lotSize: 250, strikeStep: 20, baseIV: 0.21, defaultPrice: 3050.00 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd', sector: 'Chemicals & Fertilisers', lotSize: 200, strikeStep: 50, baseIV: 0.22, defaultPrice: 2450.00 },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India', sector: 'Chemicals & Fertilisers', lotSize: 1100, strikeStep: 5, baseIV: 0.23, defaultPrice: 520.00 },
  { symbol: 'SRF', name: 'SRF Ltd (Chemicals & Refrig)', sector: 'Chemicals & Fertilisers', lotSize: 275, strikeStep: 20, baseIV: 0.27, defaultPrice: 2250.00 },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd', sector: 'Chemicals & Fertilisers', lotSize: 250, strikeStep: 20, baseIV: 0.32, defaultPrice: 2750.00 },
  { symbol: 'TATACHEM', name: 'Tata Chemicals Ltd (Soda Ash)', sector: 'Chemicals & Fertilisers', lotSize: 550, strikeStep: 10, baseIV: 0.34, defaultPrice: 1080.00 },
  { symbol: 'UPL', name: 'UPL Ltd (Agrochemicals)', sector: 'Chemicals & Fertilisers', lotSize: 1300, strikeStep: 5, baseIV: 0.36, defaultPrice: 560.00 },
  { symbol: 'PIIND', name: 'PI Industries Ltd', sector: 'Chemicals & Fertilisers', lotSize: 125, strikeStep: 50, baseIV: 0.27, defaultPrice: 4150.00 },
  { symbol: 'ATUL', name: 'Atul Ltd', sector: 'Chemicals & Fertilisers', lotSize: 75, strikeStep: 100, baseIV: 0.26, defaultPrice: 7400.00 },
  { symbol: 'COROMANDEL', name: 'Coromandel International', sector: 'Chemicals & Fertilisers', lotSize: 350, strikeStep: 20, baseIV: 0.25, defaultPrice: 1680.00 },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine International', sector: 'Chemicals & Fertilisers', lotSize: 150, strikeStep: 50, baseIV: 0.33, defaultPrice: 3450.00 },
  { symbol: 'AARTIIND', name: 'Aarti Industries Ltd', sector: 'Chemicals & Fertilisers', lotSize: 1000, strikeStep: 10, baseIV: 0.34, defaultPrice: 540.00 },

  // --- ADANI GROUP CONGLOMERATE ---
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd', sector: 'Conglomerate', lotSize: 300, strikeStep: 50, baseIV: 0.36, defaultPrice: 2840.00 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ', sector: 'Ports & Logistics', lotSize: 400, strikeStep: 20, baseIV: 0.31, defaultPrice: 1260.00 },
  { symbol: 'ATGL', name: 'Adani Total Gas Ltd', sector: 'Energy & Power', lotSize: 675, strikeStep: 10, baseIV: 0.44, defaultPrice: 720.00 },
  { symbol: 'ADANIWILMR', name: 'AWL Agri / Adani Wilmar (Fortune)', sector: 'FMCG & Consumer', lotSize: 1575, strikeStep: 5, baseIV: 0.39, defaultPrice: 335.00 },
];
